import { ClassLimits, LooseObject } from "./interfaces";

// TODO: move this to tests once logic is mostly done.
export const mathStatOnlyRooms = ["nh251", "nh259", "nh276", "nh261", "nh295"];
export const csOnlyRooms = ["sb372", "nh253", "sb010", "sb382", "hh336", "hh334", "sc203"];
// NOTE: it fails to find a solution when there are is not an extra room.
export const both = ["nh064", "a"];
export const csLabRooms = ["sb337", "sb354"];
export const bioRooms = ["sb256", "sb276", "cfaud", "hc300", "sb103"];
export const bioLabRooms = ["sb277", "dh132", "dh106", "dh124", "sb210"];

export const csRooms = [...csOnlyRooms, ...both];
export const mathStatRooms = [...mathStatOnlyRooms, ...both];

export const rooms = [
  ...mathStatOnlyRooms,
  ...csOnlyRooms,
  ...both,
  ...csLabRooms,
  ...bioRooms,
  ...bioLabRooms,
];

export const times = [
  "mwf800",
  "mwf900",
  "mwf1030",
  "mwf1130",
  "mwf1230",
  "mwf130",
  "mwf230",
  "tth830",
  "tth1030",
];

// TODO: make professor field an array.
// TODO: add more fields to ClassLimits that are appropriate.
export const userConstraints: LooseObject<ClassLimits> = {
  cs100a: { professor: "meyer", rooms: csRooms },
  cs104a: { professor: "schuurman", rooms: csRooms },
  cs104b: { professor: "schuurman", rooms: csRooms },
  cs104c: { professor: "schuurman", rooms: csRooms },
  lcs104a: { professor: "sykes", rooms: csLabRooms },
  lcs104b: { professor: "schuurman", rooms: csLabRooms },
  lcs104c: { professor: "sykes", rooms: csLabRooms },
  lcs104d: { professor: "schuurman", rooms: csLabRooms },
  lcs104e: { professor: "sykes", rooms: csLabRooms },
  cs106a: { professor: "norman", rooms: csRooms },
  lcs106a: { professor: "norman", rooms: csLabRooms },
  cs108a: { professor: "vanderlinden", rooms: csRooms },
  cs108b: { professor: "arnold", rooms: csRooms },
  lcs108a: { professor: "wieringa", rooms: csLabRooms },
  lcs108b: { professor: "arnold", rooms: csLabRooms },
  cs112a: { professor: "adams", rooms: csRooms },
  cs112b: { professor: "adams", rooms: csRooms },
  lcs112a: { professor: "norman", rooms: csLabRooms },
  lcs112b: { professor: "wieringa", rooms: csLabRooms },
  cs195a: { professor: "norman", rooms: csRooms },
  cs212a: { professor: "plantinga", rooms: csRooms },
  cs212b: { professor: "plantinga", rooms: csRooms },
  cs214a: { professor: "adams", rooms: csRooms },
  cs214b: { professor: "adams", rooms: csRooms },
  lcs214a: { professor: "meyer", rooms: csLabRooms },
  lcs214b: { professor: "meyer", rooms: csLabRooms },
  cs232a: { professor: "norman", rooms: csRooms },
  cs232b: { professor: "norman", rooms: csRooms },
  cs262a: { professor: "vanderlinden", rooms: csRooms },
  cs262b: { professor: "vanderlinden", rooms: csRooms },
  lcs262a: { professor: "vanderlinden", rooms: csLabRooms },
  lcs262b: { professor: "vanderlinden", rooms: csLabRooms },
  cs295a: { professor: "norman", rooms: csRooms },
  cs300a: { professor: "schuurman", rooms: csRooms },
  lcs300a: { professor: "schuurman", rooms: csLabRooms },
  cs332a: { professor: "norman", rooms: csRooms },
  cs336a: { professor: "norman", rooms: csRooms },
  cs342a: { professor: "bailey", rooms: csRooms },
  cs344a: { professor: "vanderlinden", rooms: csRooms },
  cs364a: { professor: "vedra", rooms: csRooms },
  cs374a: { professor: "adams", rooms: csRooms },
  cs383a: { professor: "bailey", rooms: csRooms },
  cs384a: { professor: "schuurman", rooms: csRooms },
  cs384b: { professor: "schuurman", rooms: csRooms },
  // # NOTE: skip cs390
  cs394: { professor: "bailey", rooms: csRooms },
  // # NOTE: skip cs 396/8 and CS-W60
  data101a: { professor: "bailey", rooms: csRooms },
  data101b: { professor: "bailey", rooms: csRooms },
  data175a: { professor: "brendavanderlinden", rooms: csRooms },
  data175b: { professor: "brendavanderlinden", rooms: csRooms },
  data175c: { professor: "momeyer", rooms: csRooms },
  data202a: { professor: "arnold", rooms: csRooms },
  data303: { professor: "arnold", rooms: csRooms },
  data383: { professor: "bailey", rooms: csRooms },
  idis110a: { professor: "bobeldyk", rooms: csRooms },
  math100a: { professor: "turner", rooms: mathStatRooms },
  math132a: { professor: "bolt", rooms: mathStatRooms },
  math169a: { professor: "ferdinands", rooms: mathStatRooms },
  math170a: { professor: "ferdinands", rooms: mathStatRooms },
  math171a: { professor: "bolt", rooms: mathStatRooms },
  math171b: { professor: "bolt", rooms: mathStatRooms },
  math171c: { professor: "moseley", rooms: mathStatRooms },
  math171d: { professor: "moseley", rooms: mathStatRooms },
  math172a: { professor: "sunukjian", rooms: mathStatRooms },
  math172b: { professor: "scofield", rooms: mathStatRooms },
  math172c: { professor: "kapitula", rooms: mathStatRooms },
  math190a: { professor: "scofield", rooms: mathStatRooms },
  math221a: { professor: "klanderman", rooms: mathStatRooms },
  math222a: { professor: "talsma", rooms: mathStatRooms },
  math231a: { professor: "scofield", rooms: mathStatRooms },
  math231b: { professor: "kapitula", rooms: mathStatRooms },
  math231c: { professor: "scofield", rooms: mathStatRooms },
  math251a: { professor: "scofield", rooms: mathStatRooms },
  math251b: { professor: "scofield", rooms: mathStatRooms },
  math252a: { professor: "pruim", rooms: mathStatRooms },
  math252b: { professor: "pruim", rooms: mathStatRooms },
  math255a: { professor: "moseley", rooms: mathStatRooms },
  math270a: { professor: "ferdinands", rooms: mathStatRooms },
  math271a: { professor: "ferdinands", rooms: mathStatRooms },
  math270b: { professor: "bolt", rooms: mathStatRooms },
  math271b: { professor: "bolt", rooms: mathStatRooms },
  math270c: { professor: "kapitula", rooms: mathStatRooms },
  math271c: { professor: "kapitula", rooms: mathStatRooms },
  math301a: { professor: "turner", rooms: mathStatRooms },
  math305a: { professor: "moseley", rooms: mathStatRooms },
  math323a: { professor: "genzink", rooms: mathStatRooms },
  math327a: { professor: "klanderman", rooms: mathStatRooms },
  math331a: { professor: "kapitula", rooms: mathStatRooms },
  math351a: { professor: "ferdinands", rooms: mathStatRooms },
  math355a: { professor: "kapitula", rooms: mathStatRooms },
  math359a: { professor: "klanderman", rooms: mathStatRooms },
  math361a: { professor: "ferdinands", rooms: mathStatRooms },
  math390a: { professor: "moseley", rooms: mathStatRooms },
  math391a: { professor: "moseley", rooms: mathStatRooms },
  math395a: { professor: "klanderman", rooms: mathStatRooms },
  mathw81a: { professor: "moseley", rooms: mathStatRooms },
  mathw82a: { professor: "pruim", rooms: mathStatRooms },
  stat143a: { professor: "pamplantinga", rooms: mathStatRooms },
  stat143b: { professor: "pamplantinga", rooms: mathStatRooms },
  stat143c: { professor: "barbaraadams", rooms: mathStatRooms },
  stat143d: { professor: "barbaraadams", rooms: mathStatRooms },
  stat143e: { professor: "talsma", rooms: mathStatRooms },
  stat145a: { professor: "scofield", rooms: mathStatRooms },
  stat241a: { professor: "jager", rooms: mathStatRooms },
  stat241b: { professor: "jager", rooms: mathStatRooms },
  stat241c: { professor: "jager", rooms: mathStatRooms },
  stat243a: { professor: "deruiter", rooms: mathStatRooms },
  stat245a: { professor: "deruiter", rooms: mathStatRooms },
  stat343a: { professor: "pruim", rooms: mathStatRooms },
  stat344a: { professor: "deruiter", rooms: mathStatRooms },
  stat390a: { professor: "pruim", rooms: mathStatRooms },
  // // # TODO: add engineering classes and cognates
  // bio115a: "miller",
  // bio123a: "miller",
  // bio141a: "shen",
  // bio141b: "shen",
  // lbio141a: "shen",
  // lbio141b: "grasman",
  // lbio141c: "grasman",
  // lbio141d: "shen",
  // bio160a: "grasman",
  // bio160n: "wertz",
  // lbio160a: "grasman",
  // lbio160b: "dejong",
  // lbio160c: "dejong",
  // lbio160n: "wertz",
  // bio161a: "koetje",
  // lbio161a: "miller",
  // lbio161b: "miller",
  // bio205a: "bebej",
  // lbio205a: "bebej",
  // lbio205b: "bebej",
  // lbio205c: "bebej",
  // lbio205d: "bebej",
  // lbio205e: "barrett",
  // bio206a: "dubois",
  // bio206b: "barret",
  // lbio206a: "dubois",
  // lbio206b: "barret",
  // lbio206c: "dubois",
  // lbio206d: "boldenow",
  // bio207a: "wertz",
  // bio207b: "wertz",
  // lbio207a: "wertz",
  // lbio207b: "wertz",
  // lbio207c: "wertz",
  // lbio207d: "shen",
  // lbio207e: "shen",
  // lbio207f: "shen",
  // lbio207g: "keen",
  // lbio207h: "keen",
  // lbio207i: "keen",
  // bio230a: "dornbos",
  // lbio230a: "koetje",
  // lbio230b: "barrett",
  // lbio230c: "koetje",
  // bio250a: "miller",
  // bio250b: "dejong",
  // bio295a: "koetje",
  // bio321a: "wilstermann",
  // lbio321a: "wiltermann",
  // lbio321b: "wiltermann",
  // bio331a: "boldenow",
  // lbio331a: "boldenow",
  // lbio331b: "boldenow",
  // bio332a: "dornbos",
  // lbio332a: "dornbos",
  // bio333a: "shen",
  // lbio333a: "shen",
  // bio335a: "barrett",
  // lbio335a: "boldenow",
  // bio336a: "wertz",
  // lbio336a: "wertz",
  // bio338a: "miller",
  // lbio338a: "miller",
  // bio345a: "grasman",
  // lbio345a: "grasman",
  // bio346a: "warners",
  // lbio346a: "warners",
  // bio354a: "dornbos",
  // bio364a: "koetje",
  // bio395a: "bebej",
  // bio396a: "dubois",
};
