import { Assignments } from "../packages/harmoniously/src/interfaces";

export const mathStatOnlyRooms = ["nh251", "nh259", "nh276", "nh261", "nh295"];
export const csOnlyRooms = ["sb372", "nh253", "sb010", "sb382", "hh336", "hh334", "sc203"];
// NOTE: it fails to find a solution when there are is not an extra room.
export const both = ["nh064", "a"];
export const csLabRooms = ["sb337", "sb354"];
export const bioRooms = ["sb256", "sb276", "cfaud", "hc300", "sb103"];
export const bioLabRooms = ["sb277", "dh132", "dh106", "dh124", "sb210"];

export const csRooms = [...csOnlyRooms, ...both];
export const mathStatRooms = [...mathStatOnlyRooms, ...both];

export const rooms = [
  ...mathStatOnlyRooms,
  ...csOnlyRooms,
  ...both,
  ...csLabRooms,
  ...bioRooms,
  ...bioLabRooms,
];

export const times = [
  "mwf800",
  "mwf900",
  "mwf1030",
  "mwf1130",
  "mwf1230",
  "mwf130",
  "mwf230",
  "tth830",
  "tth1030",
];

// TODO: make professor field an array.
// TODO: add more fields to ClassLimits that are appropriate.
export const userConstraintsSmall: Assignments = {
  cs100a: { times, professors: ["meyer"], rooms: csRooms },
  cs104a: { times, professors: ["schuurman"], rooms: csRooms },
  cs104b: { times, professors: ["schuurman"], rooms: csRooms },
  cs104c: { times, professors: ["schuurman"], rooms: csRooms },
  lcs104a: { times, professors: ["sykes"], rooms: csLabRooms },
};

export const userConstraints: Assignments = {
  ...userConstraintsSmall,
  lcs104b: { times, professors: ["schuurman"], rooms: csLabRooms },
  lcs104c: { times, professors: ["sykes"], rooms: csLabRooms },
  lcs104d: { times, professors: ["schuurman"], rooms: csLabRooms },
  lcs104e: { times, professors: ["sykes"], rooms: csLabRooms },
  cs106a: { times, professors: ["norman"], rooms: csRooms },
  lcs106a: { times, professors: ["norman"], rooms: csLabRooms },
  cs108a: { times, professors: ["vanderlinden"], rooms: csRooms },
  cs108b: { times, professors: ["arnold"], rooms: csRooms },
  lcs108a: { times, professors: ["wieringa"], rooms: csLabRooms },
  lcs108b: { times, professors: ["arnold"], rooms: csLabRooms },
  cs112a: { times, professors: ["adams"], rooms: csRooms },
  cs112b: { times, professors: ["adams"], rooms: csRooms },
  lcs112a: { times, professors: ["norman"], rooms: csLabRooms },
  lcs112b: { times, professors: ["wieringa"], rooms: csLabRooms },
  cs195a: { times, professors: ["norman"], rooms: csRooms },
  cs212a: { times, professors: ["plantinga"], rooms: csRooms },
  cs212b: { times, professors: ["plantinga"], rooms: csRooms },
  cs214a: { times, professors: ["adams"], rooms: csRooms },
  cs214b: { times, professors: ["adams"], rooms: csRooms },
  lcs214a: { times, professors: ["meyer"], rooms: csLabRooms },
  lcs214b: { times, professors: ["meyer"], rooms: csLabRooms },
  cs232a: { times, professors: ["norman"], rooms: csRooms },
  cs232b: { times, professors: ["norman"], rooms: csRooms },
  cs262a: { times, professors: ["vanderlinden"], rooms: csRooms },
  cs262b: { times, professors: ["vanderlinden"], rooms: csRooms },
  lcs262a: { times, professors: ["vanderlinden"], rooms: csLabRooms },
  lcs262b: { times, professors: ["vanderlinden"], rooms: csLabRooms },
  cs295a: { times, professors: ["norman"], rooms: csRooms },
  cs300a: { times, professors: ["schuurman"], rooms: csRooms },
  lcs300a: { times, professors: ["schuurman"], rooms: csLabRooms },
  cs332a: { times, professors: ["norman"], rooms: csRooms },
  cs336a: { times, professors: ["norman"], rooms: csRooms },
  cs342a: { times, professors: ["bailey"], rooms: csRooms },
  cs344a: { times, professors: ["vanderlinden"], rooms: csRooms },
  cs364a: { times, professors: ["vedra"], rooms: csRooms },
  cs374a: { times, professors: ["adams"], rooms: csRooms },
  cs383a: { times, professors: ["bailey"], rooms: csRooms },
  cs384a: { times, professors: ["schuurman"], rooms: csRooms },
  cs384b: { times, professors: ["schuurman"], rooms: csRooms },
  // # NOTE: skip cs390
  cs394: { times, professors: ["bailey"], rooms: csRooms },
  // # NOTE: skip cs 396/8 and CS-W60
  data101a: { times, professors: ["bailey"], rooms: csRooms },
  data101b: { times, professors: ["bailey"], rooms: csRooms },
  data175a: { times, professors: ["brendavanderlinden"], rooms: csRooms },
  data175b: { times, professors: ["brendavanderlinden"], rooms: csRooms },
  data175c: { times, professors: ["momeyer"], rooms: csRooms },
  data202a: { times, professors: ["arnold"], rooms: csRooms },
  data303: { times, professors: ["arnold"], rooms: csRooms },
  data383: { times, professors: ["bailey"], rooms: csRooms },
  idis110a: { times, professors: ["bobeldyk"], rooms: csRooms },
  math100a: { times, professors: ["turner"], rooms: mathStatRooms },
  math132a: { times, professors: ["bolt"], rooms: mathStatRooms },
  math169a: { times, professors: ["ferdinands"], rooms: mathStatRooms },
  math170a: { times, professors: ["ferdinands"], rooms: mathStatRooms },
  math171a: { times, professors: ["bolt"], rooms: mathStatRooms },
  math171b: { times, professors: ["bolt"], rooms: mathStatRooms },
  math171c: { times, professors: ["moseley"], rooms: mathStatRooms },
  math171d: { times, professors: ["moseley"], rooms: mathStatRooms },
  math172a: { times, professors: ["sunukjian"], rooms: mathStatRooms },
  math172b: { times, professors: ["scofield"], rooms: mathStatRooms },
  math172c: { times, professors: ["kapitula"], rooms: mathStatRooms },
  math190a: { times, professors: ["scofield"], rooms: mathStatRooms },
  math221a: { times, professors: ["klanderman"], rooms: mathStatRooms },
  math222a: { times, professors: ["talsma"], rooms: mathStatRooms },
  math231a: { times, professors: ["scofield"], rooms: mathStatRooms },
  math231b: { times, professors: ["kapitula"], rooms: mathStatRooms },
  math231c: { times, professors: ["scofield"], rooms: mathStatRooms },
  math251a: { times, professors: ["scofield"], rooms: mathStatRooms },
  math251b: { times, professors: ["scofield"], rooms: mathStatRooms },
  math252a: { times, professors: ["pruim"], rooms: mathStatRooms },
  math252b: { times, professors: ["pruim"], rooms: mathStatRooms },
  math255a: { times, professors: ["moseley"], rooms: mathStatRooms },
  math270a: { times, professors: ["ferdinands"], rooms: mathStatRooms },
  math271a: { times, professors: ["ferdinands"], rooms: mathStatRooms },
  math270b: { times, professors: ["bolt"], rooms: mathStatRooms },
  math271b: { times, professors: ["bolt"], rooms: mathStatRooms },
  math270c: { times, professors: ["kapitula"], rooms: mathStatRooms },
  math271c: { times, professors: ["kapitula"], rooms: mathStatRooms },
  math301a: { times, professors: ["turner"], rooms: mathStatRooms },
  math305a: { times, professors: ["moseley"], rooms: mathStatRooms },
  math323a: { times, professors: ["genzink"], rooms: mathStatRooms },
  math327a: { times, professors: ["klanderman"], rooms: mathStatRooms },
  math331a: { times, professors: ["kapitula"], rooms: mathStatRooms },
  math351a: { times, professors: ["ferdinands"], rooms: mathStatRooms },
  math355a: { times, professors: ["kapitula"], rooms: mathStatRooms },
  math359a: { times, professors: ["klanderman"], rooms: mathStatRooms },
  math361a: { times, professors: ["ferdinands"], rooms: mathStatRooms },
  math390a: { times, professors: ["moseley"], rooms: mathStatRooms },
  math391a: { times, professors: ["moseley"], rooms: mathStatRooms },
  math395a: { times, professors: ["klanderman"], rooms: mathStatRooms },
  mathw81a: { times, professors: ["moseley"], rooms: mathStatRooms },
  mathw82a: { times, professors: ["pruim"], rooms: mathStatRooms },
  stat143a: { times, professors: ["pamplantinga"], rooms: mathStatRooms },
  stat143b: { times, professors: ["pamplantinga"], rooms: mathStatRooms },
  stat143c: { times, professors: ["barbaraadams"], rooms: mathStatRooms },
  stat143d: { times, professors: ["barbaraadams"], rooms: mathStatRooms },
  stat143e: { times, professors: ["talsma"], rooms: mathStatRooms },
  stat145a: { times, professors: ["scofield"], rooms: mathStatRooms },
  stat241a: { times, professors: ["jager"], rooms: mathStatRooms },
  stat241b: { times, professors: ["jager"], rooms: mathStatRooms },
  stat241c: { times, professors: ["jager"], rooms: mathStatRooms },
  stat243a: { times, professors: ["deruiter"], rooms: mathStatRooms },
  stat245a: { times, professors: ["deruiter"], rooms: mathStatRooms },
  stat343a: { times, professors: ["pruim"], rooms: mathStatRooms },
  stat344a: { times, professors: ["deruiter"], rooms: mathStatRooms },
  stat390a: { times, professors: ["pruim"], rooms: mathStatRooms },
  // // # TODO: add engineering classes and cognates
  // bio115a: "miller",
  // bio123a: "miller",
  // bio141a: "shen",
  // bio141b: "shen",
  // lbio141a: "shen",
  // lbio141b: "grasman",
  // lbio141c: "grasman",
  // lbio141d: "shen",
  // bio160a: "grasman",
  // bio160n: "wertz",
  // lbio160a: "grasman",
  // lbio160b: "dejong",
  // lbio160c: "dejong",
  // lbio160n: "wertz",
  // bio161a: "koetje",
  // lbio161a: "miller",
  // lbio161b: "miller",
  // bio205a: "bebej",
  // lbio205a: "bebej",
  // lbio205b: "bebej",
  // lbio205c: "bebej",
  // lbio205d: "bebej",
  // lbio205e: "barrett",
  // bio206a: "dubois",
  // bio206b: "barret",
  // lbio206a: "dubois",
  // lbio206b: "barret",
  // lbio206c: "dubois",
  // lbio206d: "boldenow",
  // bio207a: "wertz",
  // bio207b: "wertz",
  // lbio207a: "wertz",
  // lbio207b: "wertz",
  // lbio207c: "wertz",
  // lbio207d: "shen",
  // lbio207e: "shen",
  // lbio207f: "shen",
  // lbio207g: "keen",
  // lbio207h: "keen",
  // lbio207i: "keen",
  // bio230a: "dornbos",
  // lbio230a: "koetje",
  // lbio230b: "barrett",
  // lbio230c: "koetje",
  // bio250a: "miller",
  // bio250b: "dejong",
  // bio295a: "koetje",
  // bio321a: "wilstermann",
  // lbio321a: "wiltermann",
  // lbio321b: "wiltermann",
  // bio331a: "boldenow",
  // lbio331a: "boldenow",
  // lbio331b: "boldenow",
  // bio332a: "dornbos",
  // lbio332a: "dornbos",
  // bio333a: "shen",
  // lbio333a: "shen",
  // bio335a: "barrett",
  // lbio335a: "boldenow",
  // bio336a: "wertz",
  // lbio336a: "wertz",
  // bio338a: "miller",
  // lbio338a: "miller",
  // bio345a: "grasman",
  // lbio345a: "grasman",
  // bio346a: "warners",
  // lbio346a: "warners",
  // bio354a: "dornbos",
  // bio364a: "koetje",
  // bio395a: "bebej",
  // bio396a: "dubois",
};
